### ISSUE TITLE
Untrusted workspaces

### ISSUE THREAD

**Issue by jtran** [SamuelCharpentier/remove-non-ascii-chars#1]
Is it possible to make this extension work in untrusted workspaces?

BTW, thanks for making this!  I use it all the time.

**Comment by SamuelCharpentier** [comment]
I'll look into this, as the trusted workspace feature was added after I made this. I'll post here when I figure this out and push an update.

You're welcome, same here, I made this because I needed it, simply ☺

**Comment by SamuelCharpentier** [comment]
There you go, It was real simple after all, you might have to go to the extension page and click on "Reload required" to update the plugin if you never close VS Code, but it works on my machine 😇

**Comment by jtran** [comment]
That works!  Thank you!
