### ISSUE TITLE
Error when using

### ISSUE THREAD

**Issue by Eleiyas** [SamuelCharpentier/remove-non-ascii-chars#2]
![image](https://user-images.githubusercontent.com/16349939/151009042-7efb6793-717c-436c-81c8-fb5266160809.png)

**Comment by Eleiyas** [comment]
![image](https://user-images.githubusercontent.com/16349939/151009125-1bf329d1-d29b-48d2-b4ee-4439cf0b49ed.png)

**Comment by SamuelCharpentier** [comment]
Hi Eleiyas, thank you for letting me know there's an issue.

I'll need a little bit more information to help you with this. 
What's the extension version number and is there an update to install for it?
What's your VS Code edition and version number?
Is it done in a trusted environment or not?
Did you try restarting VS Code?
How can I reproduce the error step by step?

I'll be waiting for your reply
