### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by rsnbusa** [SamuelCharpentier/remove-non-ascii-chars#4]
Hi. Justr loaded your extensions and the runtime status is Not Yet Activated, no matter what I do, reload vsc, etc.

When i try to use it in a big file with some chars >0x80 (specifically 0xfa) it sigve s the image shown.

![image](https://user-images.githubusercontent.com/8524715/227409463-bfb2cf2f-d5eb-437b-b5b9-068489c9fd3d.png)

Mac mini m1 Ventura vsc Version: 1.76.2

Regards.

**Comment by SamuelCharpentier** [comment]
Hi @rsnbusa. I beleive this is an issue with trusted workspaces. Make sure the file you open is in a trusted workspace. 

If you want to test, copy the content over to an empty workspace in a new file and see if it works there, VSC should fully trust a new file in an empty workpsace.

I've tested it on Macbook Air M1, using VS Code for M1. See if you are using the intel on rosetta version instead.

Let me know if this fixes your issue.
