### ISSUE TITLE
Have to Restart VSCode after every use

### ISSUE THREAD

**Issue by wesleylhandy** [SamuelCharpentier/remove-non-ascii-chars#5]
Whenever I run the Command to `Remove non Ascii characters (File)` it works for that file. However, I cannot use it a second time on any other file without closing VSCode and restarting.

**Comment by SamuelCharpentier** [comment]
I've updated the extension so the editor and document is refreshed every time the Command is used. Thank you for brigning this to my attention. I will close this but do not hesitate to write back if this still persist after you make sure you have the version 0.0.7 installed
